import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartProvider from "@/components/CartProvider";
import { Toaster } from "@/components/ui/toaster";
import MobileBrands from "@/components/MobileBrands";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rajdhani.variable}>
        <div className="fixed inset-0 z-[-10] bg-[#bdc3c7] bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,[#bdc3c7],rgba(255,255,255,0))]"></div>

        <CartProvider>
          <Header />
          {children}
          <Toaster />
          <MobileBrands />
          <Footer />
        </CartProvider>
        {/* <div className=" h-[2000px]"></div> */}
      </body>
    </html>
  );
}
